### ISSUE TITLE
Add street names

### ISSUE THREAD

**Issue by 7E25DDE7** [skyrossm/np-gangmap#12]
Here is a map that has street names on it: https://lensdump.com/i/gj7atT

**Comment by skyrossm** [comment]
I have actually looked into this: https://skyrossm.github.io/DispatchMap/
however, the street name map is not scaled/sized the same as this one so an offset function would have to be made when swapping between the two maps.

**Comment by 7E25DDE7** [comment]
Adding universal coordinates will aid in implementing #21
