### ISSUE TITLE
Fix labels being shown when category is hidden

### ISSUE THREAD

**Issue by 7E25DDE7** [skyrossm/np-gangmap#32]
When a category is disabled by default the labels are not hidden unless it is toggled on and then back off.

https://github.com/skyrossm/np-gangmap/blob/83410dedb9c35c965023a43adf484814c90b2ce9/js/app.js#L102-L159

**Comment by skyrossm** [comment]
https://github.com/skyrossm/np-gangmap/commit/e0914aff78adc8654c685130e668dd8ac013cf96
