### ISSUE TITLE
Hydra Joining LS / Lucky Pluckers removed for maldinis

### ISSUE THREAD

**Issue by Mazmol** [skyrossm/np-gangmap#37]
The Yellow Part is new Hydra 
https://nopixel.fandom.com/wiki/Hydra_Gang

https://nopixel.fandom.com/wiki/Maldini%27s_Pizzeria to replace lucky Pluckers 
https://media.discordapp.net/attachments/570006592016089119/960644344518438932/Screenshot_133.png 
![image](https://user-images.githubusercontent.com/38956955/163878097-b3554133-86af-47f0-ac4d-6101ad5f18de.png)

**Comment by 7E25DDE7** [comment]
Added in f48e7c91 and 33aa10d0.
