### ISSUE TITLE
How to run that? | I can't find source folder.

### ISSUE THREAD

**Issue by anonymousek2** [skyrossm/np-gangmap#4]
Hello- I need help with how i can run that.

What i done
1) I Cloned  repository
2) I downloaded tiles.zip
-2.5) I extracted that into np-gangmap-master\tiles
And now i don't know what to do now.

**Comment by skyrossm** [comment]
You need to have Python installed, then you can use the command `python -m SimpleHTTPServer`
You need to run this in the folder np-gangmap-master

**Comment by bihariadam** [comment]
I have a same problem , i download this script and started in resources. When i want to join my server the server say i dont have _resources file. I downloaded the python 3.8 too but , when i open the powershell window and i write the python -m SimpleHTTPServer or python -m http.server it's shows lots of error. What can i do? please help me i never used python before.

**Comment by skyrossm** [comment]
This isn't a server resource, it's a standalone web app.
