### ISSUE TITLE
update nbc on nopixel territory map website

### ISSUE THREAD

**Issue by TheWorldCollector** [skyrossm/np-gangmap#48]
![image](https://user-images.githubusercontent.com/109059860/178199611-9789da47-a00d-4f94-ab90-b9409d8a6d8e.png)
the nbc turf should be at the docks 🔻
![image](https://user-images.githubusercontent.com/109059860/178199887-1905fc57-9eed-4848-8b37-4249d878178f.png)

**Comment by 7E25DDE7** [comment]
ed4dfacea1d19db283a05f3f7027d5a22fe0953d
