### ISSUE TITLE
Map cant view

### ISSUE THREAD

**Issue by Ronak31032002** [skyrossm/np-gangmap#5]
When i downloaded the zip from your git and directly opened index.html i cant see the map in the browser and even cant select the three modes satelite road modes basically no map is getting showed to me
![image](https://user-images.githubusercontent.com/53695724/79565372-37711e80-80ce-11ea-8f2d-697d369779a7.png)

**Comment by skyrossm** [comment]
You need to run the source folder as a webserver. (Python command I have in the instructions should work)
Something like XAMPP should also work.
