### ISSUE TITLE
Add Viceroy Medical Center Region

### ISSUE THREAD

**Issue by tib0ytel** [skyrossm/np-gangmap#52]
json
	{
		"id": 0,
		"type": "Medical",
		"title": "Viceroy Medical Center",
		"notes": "Viceroy Medical Center is a secondary hospital in Los Santos.",
		"wiki_ling": "https://nopixel.fandom.com/wiki/Viceroy_Medical_Center?so=search",
		"order": 0,
		"strokecolor": "FF0000",
		"fillcolor": "FF0000",
		"latlngarray": [
			{"lat": -68.741, "lng": -37.279},
			{"lat": -69.352, "lng": -40.693},
			{"lat": -69.956, "lng": -39.550},
			{"lat": -70.110, "lng": -37.221},
			{"lat": -69.533, "lng": -35.592}
		]
	}

**Comment by skyrossm** [comment]
https://github.com/skyrossm/np-gangmap/commit/78bb2d427233011a425575c5b29e42d4842d7f22
