### ISSUE TITLE
Add El Burro Heights Fire Station Region

### ISSUE THREAD

**Issue by tib0ytel** [skyrossm/np-gangmap#53]
json
	{
		"id": 0,
		"type": "Medical",
		"title": "El Burro Heights Fire Station",
		"notes": "El Burro Heights Fire Station is an official office of EMS.",
		"wiki_ling": "https://nopixel.fandom.com/wiki/Emergency_Medical_Services",
		"order": 0,
		"strokecolor": "FF0000",
		"fillcolor": "FF0000",
		"latlngarray": [
			{"lat": -71.716, "lng": 21.124},
			{"lat": -71.735, "lng": 18.447},
			{"lat": -72.255, "lng": 18.458},
			{"lat": -72.282, "lng": 21.732}
		]
	}

**Comment by skyrossm** [comment]
https://github.com/skyrossm/np-gangmap/commit/78bb2d427233011a425575c5b29e42d4842d7f22
