### ISSUE TITLE
Unable to host server on Python 3.9

### ISSUE THREAD

**Issue by S0M3B0DYY** [skyrossm/np-gangmap#7]
1) I downloaded python 3.9.
2) I extracted the np-gangmap-master in my C: drive.
3) Then i extracted the tiles zip in the C/np-gangmap-master/tiles and replaced the existing files with the same name.
4) After that i opened cmd and did "cd\".
5) After I put that code into cmd I typed "cd np-gangmap-master".
6) After I did that, I typed "python -m SimpleHTTPServer".

When I pressed enter (I think it didnt execute because i saw no new lines and I was able to type 1 second after I executed the code) and I put "localhost:3000", but it says "This site is not available. Localhost has rejected the connection". What do I need to do?

**Comment by skyrossm** [comment]
On Python 3 the command is `python -m http.server`

**Comment by S0M3B0DYY** [comment]
> On Python 3 the command is `python -m http.server`

already tried that. doesnt work

**Comment by 7E25DDE7** [comment]
@S0M3B0DYY, It worked for me.  What command and error did you get when you tried it

**Comment by 7E25DDE7** [comment]
Note that when you launch the server it tells you what port its listening on.  In my case its port 8000.  If this doesn't work, @ me and I will reopen the issue.
```
$ python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```
